#spring.application.name=student-mangement
#spring.datasource.url=jdbc:mysql://localhost:3306/student_details
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.port=8080
#
## JPA/Hibernate settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
## Debug logging
#logging.level.com.example.student_mangement=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.datasource.url=jdbc:postgresql://dpg-cj9j1234abcd123-postgresql.render.com:5432/user_service_cj9j
spring.datasource.username=user_service_cj9j_user
spring.datasource.password=kVKvA6viKsnOZTn81EPHAS522q8By3ES
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

